# Generated by Django 6.1.1 on 2026-10-06 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicine'), ('BLOOD', 'Blood'), ('BLOOD_COMPONENT', 'Blood Component'), ('BED', 'Hospital Bed'), ('ICU', 'ICU Bed'), ('OXYGEN', 'Oxygen'), ('EQUIPMENT', 'Medical Equipment'), ('LAB', 'Laboratory Service'), ('AMBULANCE', 'Ambulance'), ('SPECIALIST', 'Specialist'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='unit', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(default='INTERNAL', max_length=30)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
