# Generated by Django 6.1.1 on 2026-10-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('BLOOD', 'Blood & Blood Components'), ('MEDICINE', 'Medicines'), ('OXYGEN', 'Oxygen & Respiratory'), ('SPECIALIST', 'Specialist / Doctor'), ('EMERGENCY', 'Emergency Services'), ('OTHER', 'Other')], default='OTHER', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('API', 'API'), ('SYSTEM', 'System')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.CharField(default='units', max_length=50),
        ),
    ]
